# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FFCAFl1uRcNpBC3u5CsMqfKvPp2LGMvQ
"""

# Personal Finance Chatbot with IBM Granite 3.2-2B
# Run this in Google Colab

# Install required packages
!pip install -q transformers accelerate gradio torch

import gradio as gr
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

# Load the IBM Granite model and tokenizer
MODEL_NAME = "ibm-granite/granite-3.2-2b-instruct"

print("Loading model... This may take a few minutes.")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
)
print("Model loaded successfully!")

# System prompts for different user types
SYSTEM_PROMPTS = {
    "student": """You are a friendly financial advisor helping students. Use simple language,
    relatable examples, and focus on topics like student loans, part-time income, budgeting
    on a tight budget, and building credit. Be encouraging and understanding of limited resources.""",

    "professional": """You are a professional financial advisor. Use sophisticated financial
    terminology, discuss investment strategies, tax optimization, retirement planning, and
    wealth management. Provide detailed analytical insights."""
}

def generate_response(message, history, user_type, temperature, max_tokens):
    """Generate chatbot response based on user input and type"""

    # Get appropriate system prompt
    system_prompt = SYSTEM_PROMPTS.get(user_type.lower(), SYSTEM_PROMPTS["professional"])

    # Build conversation context
    conversation = f"{system_prompt}\n\n"

    # Add chat history
    for human, assistant in history:
        conversation += f"User: {human}\nAssistant: {assistant}\n"

    # Add current message
    conversation += f"User: {message}\nAssistant:"

    # Tokenize input
    inputs = tokenizer(conversation, return_tensors="pt", truncation=True, max_length=2048)
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    # Generate response
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_tokens,
            temperature=temperature,
            do_sample=True,
            top_p=0.9,
            repetition_penalty=1.1,
            pad_token_id=tokenizer.eos_token_id
        )

    # Decode response
    full_response = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Extract only the assistant's response
    response = full_response.split("Assistant:")[-1].strip()

    # Clean up response
    if "User:" in response:
        response = response.split("User:")[0].strip()

    return response

def analyze_spending(expenses_text):
    """Analyze spending patterns and provide insights"""

    prompt = f"""Analyze the following expenses and provide:
1. A summary of spending by category
2. Percentage breakdown
3. Top 3 actionable recommendations to improve financial health

Expenses:
{expenses_text}

Provide a clear, structured analysis."""

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=1024)
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=500,
            temperature=0.7,
            do_sample=True,
            top_p=0.9,
            pad_token_id=tokenizer.eos_token_id
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return response.split(prompt)[-1].strip()

def create_budget_summary(income, monthly_expenses):
    """Generate a budget summary with recommendations"""

    prompt = f"""Create a comprehensive budget summary for someone with:
- Monthly Income: ${income}
- Monthly Expenses: ${monthly_expenses}

Include:
1. Savings rate and available savings
2. Budget health assessment
3. Recommendations for the 50/30/20 rule (needs/wants/savings)
4. Specific action items to improve their financial situation

Be encouraging and practical."""

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=1024)
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=400,
            temperature=0.7,
            do_sample=True,
            top_p=0.9,
            pad_token_id=tokenizer.eos_token_id
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return response.split(prompt)[-1].strip()

# Create Gradio Interface
with gr.Blocks(theme=gr.themes.Soft(), title="Personal Finance Chatbot") as demo:
    gr.Markdown("""
    # 💰 Personal Finance Chatbot
    ### Powered by IBM Granite 3.2-2B

    Get personalized financial advice on savings, taxes, investments, and budgeting!
    """)

    with gr.Tabs():
        # Chat Tab
        with gr.Tab("💬 Chat Assistant"):
            with gr.Row():
                with gr.Column(scale=3):
                    chatbot = gr.Chatbot(height=500, label="Financial Advisor")
                    msg = gr.Textbox(
                        label="Your Question",
                        placeholder="Ask me about savings, investments, taxes, budgeting...",
                        lines=2
                    )
                    with gr.Row():
                        submit = gr.Button("Send", variant="primary")
                        clear = gr.Button("Clear Chat")

                with gr.Column(scale=1):
                    user_type = gr.Radio(
                        choices=["Student", "Professional"],
                        value="Professional",
                        label="User Type",
                        info="Adjust response style"
                    )
                    temperature = gr.Slider(
                        minimum=0.1,
                        maximum=1.0,
                        value=0.7,
                        step=0.1,
                        label="Creativity",
                        info="Higher = more creative"
                    )
                    max_tokens = gr.Slider(
                        minimum=100,
                        maximum=500,
                        value=300,
                        step=50,
                        label="Response Length"
                    )

                    gr.Markdown("""
                    ### 💡 Sample Questions:
                    - How should I start investing as a student?
                    - What's the best way to save for retirement?
                    - How can I reduce my tax liability?
                    - Help me create a monthly budget
                    """)

            def respond(message, chat_history, user_type, temp, max_tok):
                bot_message = generate_response(message, chat_history, user_type, temp, max_tok)
                chat_history.append((message, bot_message))
                return "", chat_history

            msg.submit(respond, [msg, chatbot, user_type, temperature, max_tokens], [msg, chatbot])
            submit.click(respond, [msg, chatbot, user_type, temperature, max_tokens], [msg, chatbot])
            clear.click(lambda: None, None, chatbot, queue=False)

        # Spending Analysis Tab
        with gr.Tab("📊 Spending Analysis"):
            gr.Markdown("### Analyze Your Spending Patterns")
            gr.Markdown("Enter your expenses (e.g., 'Rent: $1200, Groceries: $400, Entertainment: $200')")

            expenses_input = gr.Textbox(
                label="Your Expenses",
                placeholder="Rent: $1200\nGroceries: $400\nTransport: $150\nEntertainment: $200\nUtilities: $100",
                lines=6
            )
            analyze_btn = gr.Button("Analyze Spending", variant="primary")
            analysis_output = gr.Textbox(label="Analysis & Recommendations", lines=12)

            analyze_btn.click(analyze_spending, inputs=expenses_input, outputs=analysis_output)

        # Budget Summary Tab
        with gr.Tab("📝 Budget Summary"):
            gr.Markdown("### Generate Your Budget Summary")

            with gr.Row():
                income_input = gr.Number(label="Monthly Income ($)", value=5000)
                expenses_input_budget = gr.Number(label="Monthly Expenses ($)", value=3500)

            budget_btn = gr.Button("Generate Budget Summary", variant="primary")
            budget_output = gr.Textbox(label="Your Budget Summary", lines=12)

            budget_btn.click(
                create_budget_summary,
                inputs=[income_input, expenses_input_budget],
                outputs=budget_output
            )

    gr.Markdown("""
    ---
    **Disclaimer:** This chatbot provides general financial information and should not be considered
    professional financial advice. Always consult with a qualified financial advisor for personalized guidance.
    """)

# Launch the app
demo.launch(share=True, debug=True)